[project]
name = "coran"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rhanniga", email = "ryan@venhub.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.5",
]

[project.scripts]
coran = "coran:main"

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
